<?php
/**
 * MyBB 1.6 Finnish Language Pack
 * Suomentanut Vesa Piittinen, katso http://community.mybb.com/thread-89482.html
 */

$l['nav_online'] = "Paikallaolijat";
$l['nav_onlinetoday'] = "Paikalla tänään";
$l['viewing_announcements'] = "Tarkastelee huoneen <a href=\"{1}\">{2}</a> ilmoitusta";
$l['viewing_announcements2'] = "Tarkastelee huoneen ilmoitusta";
$l['viewing_attachment'] = "Tarkastelee liitetiedostoa";
$l['viewing_attachment2'] = "Tarkastelee keskustelun <a href=\"{3}\">{2}</a> <a href=\"attachment.php?aid={1}\" target=\"_blank\">liitetiedostoa</a>";
$l['viewing_calendar'] = "Tarkastelee <a href=\"calendar.php\">kalenteria</a>";
$l['viewing_event'] = "Tarkastelee tapahtumaa";
$l['viewing_event2'] = "Tarkastelee tapahtumaa <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">Luo tapahtumaa</a>";
$l['editing_event'] = "Muokkaa tapahtumaa";
$l['editing_post'] = "Muokkaa viestiä";
$l['viewing_forum'] = "Tarkastelee huonetta";
$l['viewing_forum2'] = "Tarkastelee huonetta <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "Ohjautuu huoneeseen <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">Etusivu</a>";
$l['activating_account'] = "Aktivoi tunnusta";
$l['viewing_profile'] = "Tarkastelee profiilia";
$l['viewing_profile2'] = "Tarkastelee käyttäjän <a href=\"{1}\">{2}</a> profiilia";
$l['registering'] = "<a href=\"member.php?action=register\">Luo tunnusta</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">Kirjautuu sisään</a>";
$l['logging_in_plain'] = "Kirjautuu sisään";
$l['logging_out'] = "Kirjautuu ulos";
$l['emailing_user'] = "Lähettää sähköpostia";
$l['rating_user'] = "Arvostelee käyttäjää";
$l['viewing_memberlist'] = "Tarkastelee <a href=\"memberlist.php\">käyttäjien listaa</a>";
$l['viewing_whoposted'] = "Selvittää viestin lähettäjää";
$l['viewing_whoposted2'] = "Selvittää keskusteluun <a href=\"{1}\">{2}</a> viestin lähettänyttä";
$l['marking_read'] = "<a href=\"misc.php?action=markread&amp;my_post_key={1}\">Merkitsee kaikkea luetuksi</a>";
$l['viewing_helpdocs'] = "Tarkastelee <a href=\"misc.php?action=help\">opastetta</a>";
$l['viewing_buddylist'] = "Tarkastelee <a href=\"misc.php?action=buddypopup\">kaverilistaa</a>";
$l['viewing_smilies'] = "Tarkastelee <a href=\"misc.php?action=smilies\">hymiöitä</a>";
$l['viewing_syndication'] = "Tarkastelee <a href=\"misc.php?action=syndication\">RSS-syötettä</a>";
$l['replying_thread'] = "Vastaa keskusteluun";
$l['replying_thread2'] = "Vastaa keskusteluun <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "Aloittaa uutta keskustelua";
$l['posting_thread2'] = "Aloittaa uutta keskustelua huoneeseen <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "Tarkastelee <a href=\"online.php\">paikallaolijoita</a>";
$l['viewing_woltoday'] = "Tarkastelee <a href=\"online.php?action=today\">tänään paikalla olleita</a>";
$l['creating_poll'] = "Luo kyselyä";
$l['editing_poll'] = "Muokkaa kyselyä";
$l['viewing_pollresults'] = "Tarkastelee kyselyä";
$l['voting_poll'] = "Antaa ääntä kyselyyn";
$l['using_modtools'] = "Suorittaa valvojan toimenpiteitä";
$l['sending_pm'] = "Lähettää yksityisviestiä";
$l['reading_pm'] = "Lukee yksityisviestiä";
$l['editing_pmfolders'] = "Muokkaa yksityisviestien kansioita";
$l['using_pmsystem'] = "Käyttää yksityisviestijärjestelmää";
$l['reporting_post'] = "Ilmiantaa viestiä";
$l['searching_forum'] = "<a href=\"search.php\">Suorittaa hakua</a> huoneessa {1}";
$l['reading_thread'] = "Lukee keskustelua";
$l['reading_thread2'] = "Lukee keskustelua <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "Tarkastelee vastuuhenkilöitä";
$l['viewing_stats'] = "Tarkastelee keskustelualueen tilastoja";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">Päivittää profiilia</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">Päivittää asetuksia</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">Muokkaa allekirjoitusta</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">Vaihtaa avataria</a>";
$l['viewing_subscriptions'] = "Tarkastelee <a href=\"usercp.php?action=subscriptions\">tilauksia</a>";
$l['viewing_favorites'] = "Tarkastelee <a href=\"usercp.php?action=favorites\">suosikkeja</a>";
$l['editing_pad'] = "Muokkaa <a href=\"usercp.php?action=notepad\">muistiota</a>";
$l['editing_password'] = "Vaihtaa <a href=\"usercp.php?action=password\">salasanaa</a>";
$l['user_cp'] = "Tarkastelee <a href=\"usercp.php\">tunnuksen asetuksia</a>";
$l['viewing_portal'] = "Tarkastelee <a href=\"portal.php\">sivuston portaalia</a>";
$l['viewing_noperms'] = "Lukee \"ei oikeuksia\" -viestiä";
$l['unknown_location'] = "<a href=\"{1}\">Tuntematon sijainti</a>";
$l['giving_reputation'] = "Antaa arvostusta käyttäjälle <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report'] = "Tarkastelee <a href=\"{1}\">käyttäjän {2} arvostusta</a>";
$l['viewing_reputation_report2'] = "Tarkastelee arvostusta";
$l['member_resendactivation'] = "Lähettää tunnuksen aktivointitietoja";
$l['member_lostpw'] = "Vastaanottaa <a href=\"member.php?action=lostpw\">unohtunutta salasanaa</a>";
$l['sending_thread'] = "Lähettää keskustelua ystävälle";
$l['guest'] = "Vieras";
$l['page'] = "Sivu";
$l['users_online'] = "Paikallaolijat";
$l['on_username'] = "Tunnus";
$l['time'] = "Aika";
$l['location'] = "Sijainti";
$l['online_today'] = "Paikalla tänään";
$l['refresh_page'] = "Päivitä tämä sivu";
$l['online_online_plural'] = "kävijää";
$l['online_online_singular'] = "kävijä";
$l['online_member_plural'] = "käyttäjät";
$l['online_member_singular'] = "käyttäjä";
$l['online_anon_plural'] = "on";
$l['online_anon_singular'] = "on";
$l['online_guest_plural'] = "vierasta";
$l['online_guest_singular'] = "vieras";
$l['online_count'] = "{1} {2} aktiivisena kuluneen {3} minuutin aikana ({4} {5}, {6} joista {7} näkymätöntä ja {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Isäntänimi:";
$l['if_resolvable'] = "(jos selvitettävissä)";
$l['admin_options'] = "Ylläpidon toiminnot:";
$l['search_regip_users'] = "Hae käyttäjiä, jotka ovat luoneet tunnuksen tästä IP-osoitteesta";
$l['search_postip_users'] = "Hae käyttäjiä, jotka ovat kirjoittaneet tästä IP-osoitteesta";
$l['lookup'] = "[selvitä]";
$l['member_online_today'] = "<strong>1</strong> käyttäjä tänään";
$l['members_were_online_today'] = "<strong>{1}</strong> käyttäjää tänään";
$l['member_online_hidden'] = " (yksi oli näkymätön)";
$l['members_online_hidden'] = " ({1} olivat näkymättömiä)";
$l['rating_thread'] = "Arvostelee keskustelua";
$l['viewing_imcenter'] = "Tarkastelee pikaviestintä";
$l['managing_favorites'] = "Hallitsee suosikkeja";
$l['managing_subscriptions'] = "Hallitsee tilauksia";
$l['managing_group'] = "Hallitsee ryhmää";
$l['viewing_modcp'] = "Tarkastelee valvontakeskusta";
$l['viewing_modlogs'] = "Tarkastelee valvontalokia";
$l['managing_announcements'] = "Hallitsee ilmoituksia";
$l['search_for_user'] = "Etsii käyttäjistä";
$l['managing_warninglogs'] = "Hallitsee varoituslokia";
$l['searching_ips'] = "Etsii IP-osoitteista";
$l['viewing_reports'] = "Katselee ilmoitettuja viestejä";
$l['adding_announcement'] = "Luo ilmoitusta";
$l['deleting_announcement'] = "Poistaa ilmoitusta";
$l['editing_announcement'] = "Muokkaa ilmoitusta";
$l['managing_modqueue'] = "Hallitsee valvontajonoa";
$l['editing_user_profiles'] = "Muokkaa käyttäjien profiileja";
$l['managing_bans'] = "Hallitsee banneja";
$l['revoking_warning'] = "Peruu varoitusta";
$l['warning_user'] = "Varoittaa käyttäjää";
$l['viewing_warning'] = "Tarkastelee varoitusta";
$l['managing_warnings'] = "Hallitsee varoituksia";
$l['changing_dst'] = "Siirtyy talvi- tai kesäaikaan";
$l['printing_thread'] = "Tulostaa keskustelua";
$l['printing_thread2'] = "Tulostaa keskustelua <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Hallitsee kaveri- tai estolistaansa";
?>